"""Update schema to match current models

Revision ID: 74b90a13c84b
Revises: 
Create Date: 2025-11-16 16:21:34.662226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74b90a13c84b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('physical_sets')
    op.drop_table('limit_cases')
    op.drop_table('anger_cases')
    op.drop_index(op.f('ix_items_date'), table_name='items')
    op.drop_index(op.f('ix_items_description'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_table('tens')
    op.add_column('big_sets', sa.Column('crated', sa.DateTime(), nullable=True))
    op.alter_column('big_sets', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('big_sets', 'finished',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_big_sets_crated'), 'big_sets', ['crated'], unique=False)
    op.create_index(op.f('ix_big_sets_description'), 'big_sets', ['description'], unique=False)
    op.create_index(op.f('ix_big_sets_finished'), 'big_sets', ['finished'], unique=False)
    op.create_index(op.f('ix_big_sets_id'), 'big_sets', ['id'], unique=False)
    op.drop_column('big_sets', 'created')
    op.alter_column('sets', 'duration',
               existing_type=postgresql.INTERVAL(),
               nullable=True,
               existing_server_default=sa.text("'00:00:00'::interval"))
    op.alter_column('sets', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('sets', 'comments',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('sets', 'distractions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_sets_date'), 'sets', ['date'], unique=False)
    op.create_index(op.f('ix_sets_description'), 'sets', ['description'], unique=False)
    op.create_index(op.f('ix_sets_id'), 'sets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sets_id'), table_name='sets')
    op.drop_index(op.f('ix_sets_description'), table_name='sets')
    op.drop_index(op.f('ix_sets_date'), table_name='sets')
    op.alter_column('sets', 'distractions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('sets', 'comments',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sets', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sets', 'duration',
               existing_type=postgresql.INTERVAL(),
               nullable=False,
               existing_server_default=sa.text("'00:00:00'::interval"))
    op.add_column('big_sets', sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_big_sets_id'), table_name='big_sets')
    op.drop_index(op.f('ix_big_sets_finished'), table_name='big_sets')
    op.drop_index(op.f('ix_big_sets_description'), table_name='big_sets')
    op.drop_index(op.f('ix_big_sets_crated'), table_name='big_sets')
    op.alter_column('big_sets', 'finished',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('big_sets', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_column('big_sets', 'crated')
    op.create_table('tens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tens_pkey'))
    )
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('distractions', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_description'), 'items', ['description'], unique=False)
    op.create_index(op.f('ix_items_date'), 'items', ['date'], unique=False)
    op.create_table('anger_cases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.CheckConstraint('1 <= level AND level <= 5', name=op.f('anger_cases_level_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('anger_cases_pkey'))
    )
    op.create_table('limit_cases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mine_pkey'))
    )
    op.create_table('physical_sets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('physical_sets_pkey'))
    )
    # ### end Alembic commands ###
