"""initial schema

Revision ID: e6b5b24e3866
Revises: 
Create Date: 2026-03-16 12:02:35.915261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b5b24e3866'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('big_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_big_sets_created'), 'big_sets', ['created'], unique=False)
    op.create_index(op.f('ix_big_sets_description'), 'big_sets', ['description'], unique=False)
    op.create_index(op.f('ix_big_sets_finished'), 'big_sets', ['finished'], unique=False)
    op.create_index(op.f('ix_big_sets_id'), 'big_sets', ['id'], unique=False)
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('distractions', sa.Integer(), nullable=True),
    sa.Column('big_set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['big_set_id'], ['big_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sets_big_set_id'), 'sets', ['big_set_id'], unique=False)
    op.create_index(op.f('ix_sets_date'), 'sets', ['date'], unique=False)
    op.create_index(op.f('ix_sets_description'), 'sets', ['description'], unique=False)
    op.create_index(op.f('ix_sets_id'), 'sets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sets_id'), table_name='sets')
    op.drop_index(op.f('ix_sets_description'), table_name='sets')
    op.drop_index(op.f('ix_sets_date'), table_name='sets')
    op.drop_index(op.f('ix_sets_big_set_id'), table_name='sets')
    op.drop_table('sets')
    op.drop_index(op.f('ix_big_sets_id'), table_name='big_sets')
    op.drop_index(op.f('ix_big_sets_finished'), table_name='big_sets')
    op.drop_index(op.f('ix_big_sets_description'), table_name='big_sets')
    op.drop_index(op.f('ix_big_sets_created'), table_name='big_sets')
    op.drop_table('big_sets')
    # ### end Alembic commands ###
