"""Update schema to match current models

Revision ID: e708c4a75ca6
Revises: 74b90a13c84b
Create Date: 2025-11-16 16:32:07.601044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e708c4a75ca6'
down_revision: Union[str, Sequence[str], None] = '74b90a13c84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('big_sets', sa.Column('created', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_big_sets_crated'), table_name='big_sets')
    op.create_index(op.f('ix_big_sets_created'), 'big_sets', ['created'], unique=False)
    op.drop_column('big_sets', 'crated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('big_sets', sa.Column('crated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_big_sets_created'), table_name='big_sets')
    op.create_index(op.f('ix_big_sets_crated'), 'big_sets', ['crated'], unique=False)
    op.drop_column('big_sets', 'created')
    # ### end Alembic commands ###
